<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ExtendedDesertFestival</AssemblyName>
    <RootNamespace>ExtendedDesertFestival</RootNamespace>
    <Version>1.1.1</Version>
    <TargetFramework>net6.0</TargetFramework>
    <Platforms>AnyCPU</Platforms>
    <EnableModDeploy>false</EnableModDeploy>
    <OutputPath>.</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.1.1" />
  </ItemGroup>
</Project>